CREATE TABLE IF NOT EXISTS usuarios(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    cpf VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    login VARCHAR(200) NOT NULL,
    senha VARCHAR(200) NOT NULL,
    role VARCHAR(200) NOT NULL,
    ativo BOOLEAN NOT NULL
)